### ISSUE TITLE
circumvent escapes through potential `throw` calls

### ISSUE THREAD

**Issue by aviatesk** [aviatesk/EscapeAnalysis.jl#15]
## Problem

After #12 , we will escape all the arguments of a bulit-in call that _may_ throw, using "effect-freeness" checks computed by inlinear.

#12 is necessary to fix #6, e.g. objects can certainly escape as an exception.
```julia
julia> analyze_escapes((Any,)) do a
           getfield(a, :may_not_field)
       end
var"#11#12"(_2::Any →)
1 ↑ 1 ─ %1 = Main.getfield(_2, :may_not_field)::Any
2 ◌ └──      return %1
```

But now we end up with _much_ looser analysis accuracy.
The "effect-freeness" check can fail to prove no-throw for very basic builtins like `getfield`.
E.g. in the following case, `getfield(::RefValue{String}, :x)` can't be proven to be no-throw because of [the `datatype_min_ninitialized` check](https://github.com/JuliaLang/julia/blob/94b9d66b10e8e3ebdb268e4be5f7e1f43079ad4e/base/compiler/tfuncs.jl#L745):
```julia
julia> analyze_escapes() do
           r = Ref("Hi")
           r[]
       end
var"#13#14"(_2::Base.RefValue{String} ↓)
1 → 1 ─ %1 = %new(Base.RefValue{String}, "Hi")::Base.RefValue{String}
2 ↑ │   %2 = Base.getfield(%1, :x)::String # escape !
3 ◌ └──      return %2
```

And more importantly, most array operations (i.e. `arrayref`/`arrayset`) will inevitably escape since there is implicit `BoundError` check but inference doesn't analyze array shape in general:
```julia
julia> analyze_escapes() do
           a = [0,1,2]
           a[2]
       end
var"#15#16"(_2::Vector{Int64} ↓)
 1 → 1 ─ %1  = Core.tuple(0, 1, 2)::Core.Const((0, 1, 2))
 2 → │   %2  = $(Expr(:foreigncall, :(:jl_alloc_array_1d), Vector{Int64}, svec(Any, Int64), 0, :(:ccall), Vector{Int64}, 3, 3))::Vector{Int64}
 3 ◌ │         Base.arraysize(%2, 1)::Int64
 4 ◌ └──       goto #7 if not true
 5 → 2 ┄ %5  = φ (#1 => 1, #6 => %17)::Int64
 6 ◌ │   %6  = φ (#1 => 1, #6 => %18)::Int64
 7 → │   %7  = φ (#1 => 1, #6 => %10)::Int64
 8 → │   %8  = Base.getfield(%1, %5, true)::Int64
 9 ◌ │         Base.arrayset(false, %2, %8, %7)::Vector{Int64}
10 → │   %10 = Base.add_int(%7, 1)::Int64
11 ◌ │   %11 = (%6 === 3)::Bool
12 ◌ └──       goto #4 if not %11
13 ◌ 3 ─       Base.nothing::Nothing
14 ◌ └──       goto #5
15 → 4 ─ %15 = Base.add_int(%6, 1)::Int64
16 ◌ └──       goto #5
17 → 5 ┄ %17 = φ (#4 => %15)::Int64
18 ◌ │   %18 = φ (#4 => %15)::Int64
19 ◌ │   %19 = φ (#3 => true, #4 => false)::Bool
20 ◌ │   %20 = Base.not_int(%19)::Bool
21 ◌ └──       goto #7 if not %20
22 ◌ 6 ─       goto #2
23 ◌ 7 ┄       goto #8
24 ↑ 8 ─ %24 = Base.arrayref(true, %2, 2)::Int64  # escape !
25 ◌ └──       return %24
```

## Solution ideas

There are mainly two solutions:
1. we can improve inference and improve "effect-freeness" check – e.g. introduce new lattice to recognize uninitialized fields, introduce shape analysis
2. copy an `throw`n object from stack to heap on exception when it's valid

The first option will improve inference in general and benefit other optimizations, 
but it needs much more works; especially introducing lattice element is hard under the current lattice implementation and we will rather need lattice overhaul before that.
So the second one will be the best option for us especially within this GSoC term.

## The conditions when we can "copy from stack to heap on exception"

After the discussion with @vtjnash, I think we need to prove that two conditions hold in order to circumvent no-throw checks:
1. there is no overlap of lifetimes of an `throw`n object and exception object
2. the object that may `throw` doesn't have a finalizer

### Condition 1. No lifetime overlap

The first condition is necessary because otherwise "the copy on exception" would be invalid:
```julia
local o = make_o()
try
    setfield!(o, maybe_undefined, "foo") # we can't copy `o` from stack to heap here because there is an overlap of `o` and `err`
catch err
    o.x = "bar"
    print(err.x)
end
```
In order to analyze it, I think the simple lexical (non-interprocedural) analysis would be enough because an exception can only be handled within `try/catch` clause.

### Condition 2. No finalizer

If the object in question has the finalizer, then we shouldn't allocate it on the stack.
This is because the finalizer can't be safely hooked when it can refer to the stack, which may have been reused or abandoned:
```julia
local o = open_o() # we shouldn't allocate `o` in the stack here
finalize(o) do o
    close(o)
end
checkbounds(a, i) # may throw
return read(o) # we can call `finalize(o)` here
```

To circumvent this limitation, we can think of 1.) calling all finalizers of local variables on the stack on exception, 2.) unwinding the stack and call finalizers.
But they would fairly complicate the implementation.
And in the first place, the benefit of stack allocation would be negligible in the presence of the cost of the finalizer call.

**Comment by TH3CHARLie** [comment]
Let me try to understand this. The current check is strict because we have to prevent escapes via throw, but this causes much looser analysis. To gain an accurate analysis and the ability to prevent escapes via throw. We do not use the effect-free check as it is too strict, instead, we modify the runtime to do a stack-to-heap promotion if we find a NoEscape object (therefore stack allocated) is thrown.

**Comment by aviatesk** [comment]
> We do not use the effect-free check as it is too strict

No, we will still use the effect-freeness check, but in a case when it judges a call may throw, we will make additional efforts to allocate objects on stack even when it can throw.

> instead, we modify the runtime to do a stack-to-heap promotion if we find a NoEscape object (therefore stack allocated) is thrown.

`The conditions when we can "copy from stack to heap on exception"` explains when we can allocate objects on stack even when it may throw.

**Comment by TH3CHARLie** [comment]
> 
> No, we will still use the effect-freeness check, but in a case when it judges a call may throw, we will make additional efforts to allocate objects on stack even when it can throw.
> 

that is, we allocate the object on stack even though it is analyzed as an escape within a call that may throw?

**Comment by aviatesk** [comment]
When it is valid, yes. 

We will make the following additional checks when inlinear can't prove a call is no-throw:
> 1. there is no overlap of lifetimes of an thrown object and exception object
> 2. the object that may throw doesn't have a finalizer
