### ISSUE TITLE
Port EscapeAnalysis to Base.Compiler

### ISSUE THREAD

**Issue by TH3CHARLie** [aviatesk/EscapeAnalysis.jl#26]
This issue tracks the progress of porting `EscapeAnalysis.jl` to `Base.Compiler` in Julia main repo.

**Comment by TH3CHARLie** [comment]
Currently, I am porting `EscapeAnalysis.jl` to https://github.com/TH3CHARLie/julia to develop heap-to-stack optimizations. The newly added pass is disabled by default to prevent bootstrapping errors.

**Comment by aviatesk** [comment]
If you have a public branch you're working on, we can have a review or answer questions based on that :)

We may also want to "backport" it here, since we will need the modifications you made there anyway.
